Module RibbonConstants

  Public Const RIBBON_MAIN As String = "B200"
  Public Const RIBBON_MAIN_ANCESTOR As String = RIBBON_MAIN + ".G2"
  Public Const RIBBON_MAIN_ANCESTRY As String = RIBBON_MAIN + ".G3"
  Public Const RIBBON_MAIN_ANCESTRY_FACTS As String = RIBBON_MAIN_ANCESTRY + ".I9"
  Public Const RIBBON_MAIN_ANCESTRY_FAN As String = RIBBON_MAIN_ANCESTRY + ".I12"
  Public Const RIBBON_MAIN_ANCESTRY_GALLERY As String = RIBBON_MAIN_ANCESTRY + ".I"
  Public Const RIBBON_MAIN_ANCESTRY_HINTS As String = RIBBON_MAIN_ANCESTRY + ".I"
  Public Const RIBBON_MAIN_ANCESTRY_PEDIGREE As String = RIBBON_MAIN_ANCESTRY + ".I11"
  Public Const RIBBON_MAIN_ANCESTRY_STORY As String = RIBBON_MAIN_ANCESTRY + ".I"
  Public Const RIBBON_MAIN_ANCESTRY_TREE As String = RIBBON_MAIN_ANCESTRY + ".I10"
  Public Const RIBBON_MAIN_CENSUS As String = RIBBON_MAIN + ".G6"
  Public Const RIBBON_MAIN_CENSUS_UNIFIED As String = RIBBON_MAIN_CENSUS + ".I17"
  Public Const RIBBON_MAIN_TOOLS As String = RIBBON_MAIN + ".G5"
  Public Const RIBBON_MAIN_TOOLS_GALLERY As String = RIBBON_MAIN_TOOLS + ".I18"
  Public Const RIBBON_MAIN_TOOLS_NOTEBOOK As String = RIBBON_MAIN_TOOLS + ".I19" '
End Module