Public Enum UriTrackingGroupEnum
  CUSTOM = 0
  ANCESTRY_FACTS_PERSON
  ANCESTRY_GALLERY_PERSON
  ANCESTRY_HINTS_PERSON
  ANCESTRY_STORY_PERSON
  ANCESTRY_GROUPVIEW_FAMILY
  ANCESTRY_TREEVIEW_PERSON
  ANCESTRY_FANVIEW_PERSON
  ANCESTRY_PEDIGREEVIEW_PERSON
  ANCESTRY_TREEVIEW_FAMILY
  ANCESTRY_GALLERY_TREE
  ANCESTRY_OVERVIEW_TREE
  ANCESTRY_SETTINGS_TREE
  ANCESTRY_HOME
  ANCESTRY_HOME_LOGGEDOUT
  ANCESTRY_HINTS_TREE
  ANCESTRY_MESSAGES
  ANCESTRY_DNA
  ANCESTRY_VIEWER_IMAGE
  ANCESTRY_VIEWER_MEDIA
  ANCESTRY_SEARCH
  ANCESTRY_LOGIN
  ANCESTRY
  NEWSPAPERS
  FINDAGRAVE_MEMORIAL
  FINDAGRAVE_VIEWER_IMAGE
  FINDAGRAVE
End Enum