'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AncestryAssistant.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ancestry_dna() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ancestry_dna", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ancestry_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ancestry_logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ancestry_logo_lg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ancestry_logo_lg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ancestry_view_fan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ancestry_view_fan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ancestry_view_gallery() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ancestry_view_gallery", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ancestry_view_hint() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ancestry_view_hint", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ancestry_view_pedigree() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ancestry_view_pedigree", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ancestry_view_story() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ancestry_view_story", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ancestry_view_tree() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ancestry_view_tree", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property back_circle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("back_circle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property census_lg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("census_lg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property clipboard_copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clipboard-copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property clipboard_cut() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clipboard-cut", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property clipboard_paste() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("clipboard-paste", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property col_header_filtered() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("col-header-filtered", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property col_header_sort_asc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("col-header-sort-asc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property col_header_sort_desc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("col-header-sort-desc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dropdown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dropdown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property event_birth() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("event_birth", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property event_death() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("event_death", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property event_education() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("event_education", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property event_marriage() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("event_marriage", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property familysearch_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("familysearch_logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property familysearch_logo_lg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("familysearch_logo_lg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property filepage_back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("filepage_back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property filepage_home() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("filepage_home", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property filepage_new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("filepage_new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property filepage_open() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("filepage_open", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property findagrave_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("findagrave_logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property findagrave_logo_lg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("findagrave_logo_lg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fold3_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fold3_logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fold3_logo_lg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fold3_logo_lg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property font_bold() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font-bold", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property font_color() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font-color", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property font_italic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font-italic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property font_size_decrease() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font-size-decrease", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property font_size_increase() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font-size-increase", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property font_underline() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("font-underline", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property form_close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("form-close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property form_max() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("form-max", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property form_min() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("form-min", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property gallery_lg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("gallery_lg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image_crop() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image_crop", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image_fit_all() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image_fit_all", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image_fit_horizontal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image_fit_horizontal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image_fit_vertical() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image_fit_vertical", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image_flip_horizontal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image_flip_horizontal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property image_flip_vertical() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("image_flip_vertical", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to window.addEventListener(&apos;click&apos;, function () {
        '''  var evnt = {};
        '''  evnt.ControlKey = &quot;&quot;;
        '''  evnt.EventName = &quot;WindowClick&quot;;
        '''  evnt.DataSetName = &quot;&quot;;
        '''  evnt.EventArg = &quot;&quot;;
        '''  window.chrome.webview.postMessage(evnt);
        '''});.
        '''</summary>
        Friend ReadOnly Property IncludeJSFocus() As String
            Get
                Return ResourceManager.GetString("IncludeJSFocus", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to document.addEventListener(&apos;DOMContentLoaded&apos;, function () {
        '''  var x = document.createElement(&apos;STYLE&apos;);
        '''  x.appendChild(document.createTextNode(&apos;::-webkit-scrollbar {width: 14px;background-color: #2e2e2e;}&apos;));
        '''  x.appendChild(document.createTextNode(&apos;::-webkit-scrollbar-corner {background-color: #2e2e2e;}&apos;));
        '''  x.appendChild(document.createTextNode(&apos;::-webkit-scrollbar-thumb {width: 14px;border-color: #2e2e2e;border-style: solid;border-size: .5px;background-color: #4d4d4d;}&apos;));
        '''  x.appendChild(document. [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property IncludeJSScrollbars() As String
            Get
                Return ResourceManager.GetString("IncludeJSScrollbars", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to window.MyAncestryAPI = {
        '''  ctlType: &quot;&quot;,
        '''  ctlKey: &quot;&quot;,
        '''  ctlDataSet: &quot;&quot;,
        '''  selectedRID: -1,
        '''  selectedText: &quot;&quot;,
        '''  itemType: &quot;none&quot;,
        '''  itemCount: 0,
        '''  itemVisibleCount: 0,
        '''  filter: &quot;&quot;,
        '''  columnCount: 0,
        '''  data: chrome.webview.hostObjects.sync.DataMgr,
        '''  metadata: {},
        '''  setControlFocus: function () { document.body.className = &apos;webcontrol hasfocus&apos;; },
        '''  removeControlFocus: function () { document.body.className = &apos;webcontrol&apos;; },
        '''  addDataHandlers: function () {
        '''    chrome.webview.hostObjects.s [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property JSImageList() As String
            Get
                Return ResourceManager.GetString("JSImageList", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to window.MyAncestryAPI = {
        '''  ctlType: &quot;&quot;,
        '''  ctlKey: &quot;&quot;,
        '''  ctlDataSet: &quot;&quot;,
        '''  selectedRID: -1,
        '''  selectedText: &quot;&quot;,
        '''  itemType: &quot;none&quot;,
        '''  itemCount: 0,
        '''  itemVisibleCount: 0,
        '''  filter: &quot;&quot;,
        '''  columnCount: 0,
        '''  data: chrome.webview.hostObjects.sync.DataMgr,
        '''  metadata: {},
        '''  setControlFocus: function () { document.body.className = &apos;webcontrol hasfocus&apos;; },
        '''  removeControlFocus: function () { document.body.className = &apos;webcontrol&apos;; },
        '''  addDataHandlers: function () {
        '''    chrome.webview.hostObjects.s [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property JSListBox() As String
            Get
                Return ResourceManager.GetString("JSListBox", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to window.MyAncestryAPI = {
        '''  ctlType: &quot;&quot;,
        '''  ctlKey: &quot;&quot;,
        '''  ctlDataSet: &quot;&quot;,
        '''  selectedRID: -1,
        '''  selectedText: &quot;&quot;,
        '''  itemType: &quot;none&quot;,
        '''  itemCount: 0,
        '''  itemVisibleCount: 0,
        '''  filter: &quot;&quot;,
        '''  columnCount: 0,
        '''  data: chrome.webview.hostObjects.sync.DataMgr,
        '''  metadata: {},
        '''  setControlFocus: function () { document.body.className = &apos;webcontrol hasfocus&apos;; },
        '''  removeControlFocus: function () { document.body.className = &apos;webcontrol&apos;; },
        '''  addDataHandlers: function () {
        '''    chrome.webview.hostObjects.s [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property JSTable() As String
            Get
                Return ResourceManager.GetString("JSTable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property location() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("location", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property missing_profile() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("missing_profile", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property missing_profile_female() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("missing_profile_female", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property missing_profile_male() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("missing_profile_male", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property newspaper_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("newspaper_logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property newspaper_logo_lg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("newspaper_logo_lg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property notebook_lg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("notebook_lg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property notebook_page_new() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("notebook-page-new", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property panel_header_bgpattern() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("panel-header-bgpattern", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property panel_header_close() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("panel-header-close", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property panel_header_menu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("panel-header-menu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property panel_header_pin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("panel-header-pin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property panel_header_unpinned() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("panel-header-unpinned", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property panel_search() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("panel-search", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property refresh() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("refresh", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {
        '''  &quot;bars&quot;: [
        '''    {
        '''      &quot;name&quot;: &quot;FILE&quot;,
        '''      &quot;text&quot;: &quot;File&quot;,
        '''      &quot;id&quot;: 0,
        '''      &quot;showpage&quot;: true,
        '''      &quot;groups&quot;: []
        '''    }
        '''  ]
        '''}.
        '''</summary>
        Friend ReadOnly Property Ribbon() As String
            Get
                Return ResourceManager.GetString("Ribbon", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {
        '''  &quot;bars&quot;: [
        '''    {
        '''      &quot;name&quot;: &quot;ANCESTOR&quot;,
        '''      &quot;text&quot;: &quot;Ancestor&quot;,
        '''      &quot;id&quot;: 200,
        '''      &quot;enabled&quot;: false,
        '''      &quot;groups&quot;: [
        '''        {
        '''          &quot;name&quot;: &quot;ANCESTOR_PROFILE&quot;,
        '''          &quot;text&quot;: &quot;Ancestor&quot;,
        '''          &quot;id&quot;: 2,
        '''          &quot;showpanel&quot;: true,
        '''          &quot;items&quot;: [
        '''            {
        '''              &quot;name&quot;: &quot;ANCESTOR_PROFILE_IMAGE&quot;,
        '''              &quot;id&quot;: 4,
        '''              &quot;itemtype&quot;: &quot;RIButton&quot;,
        '''              &quot;attributes&quot;: [
        '''                //{
        '''                //  &quot;attribute&quot;: &quot;ImageFr [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Ribbon_AncestryBar() As String
            Get
                Return ResourceManager.GetString("Ribbon_AncestryBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ribbon_button_dropdown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ribbon-button-dropdown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {
        '''  &quot;bars&quot;: [
        '''    {
        '''      &quot;name&quot;: &quot;BAR_FILE&quot;,
        '''      &quot;text&quot;: &quot;File&quot;,
        '''      &quot;id&quot;: 0,
        '''      &quot;visible&quot;: true,
        '''      &quot;enabled&quot;: true,
        '''      &quot;showpage&quot;: true,
        '''      &quot;groups&quot;: []
        '''    },
        '''    {
        '''      &quot;name&quot;: &quot;BAR_ANCESTOR&quot;,
        '''      &quot;text&quot;: &quot;Ancestor&quot;,
        '''      &quot;id&quot;: 200,
        '''      &quot;attributes&quot;: [
        '''        {
        '''          &quot;attribute&quot;: &quot;enabled&quot;,
        '''          &quot;value&quot;: false
        '''        }
        '''      ],
        '''      &quot;groups&quot;: [
        '''        {
        '''          &quot;id&quot;: 2
        '''        },
        '''        { &quot;id&quot;: 3 },
        '''        { &quot;id&quot;: 5 },
        '''        { &quot;id&quot;: 6  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Ribbon_ImageEditorBar() As String
            Get
                Return ResourceManager.GetString("Ribbon_ImageEditorBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {
        '''  &quot;bars&quot;: [
        '''    {
        '''      &quot;name&quot;: &quot;BAR_FILE&quot;,
        '''      &quot;text&quot;: &quot;File&quot;,
        '''      &quot;id&quot;: 0,
        '''      &quot;visible&quot;: true,
        '''      &quot;enabled&quot;: true,
        '''      &quot;showpage&quot;: true,
        '''      &quot;groups&quot;: []
        '''    },
        '''    {
        '''      &quot;name&quot;: &quot;BAR_ANCESTOR&quot;,
        '''      &quot;text&quot;: &quot;Ancestor&quot;,
        '''      &quot;id&quot;: 200,
        '''      &quot;attributes&quot;: [
        '''        {
        '''          &quot;attribute&quot;: &quot;enabled&quot;,
        '''          &quot;value&quot;: false
        '''        }
        '''      ],
        '''      &quot;groups&quot;: [
        '''        {
        '''          &quot;id&quot;: 2
        '''        },
        '''        { &quot;id&quot;: 3 },
        '''        { &quot;id&quot;: 5 },
        '''        { &quot;id&quot;: 6  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Ribbon_NotesBar() As String
            Get
                Return ResourceManager.GetString("Ribbon_NotesBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {
        '''  &quot;bars&quot;: [
        '''    {
        '''      &quot;name&quot;: &quot;RESEARCH&quot;,
        '''      &quot;text&quot;: &quot;Research&quot;,
        '''      &quot;id&quot;: 400,
        '''      &quot;visible&quot;: true,
        '''      &quot;groups&quot;: [
        '''        {
        '''          &quot;name&quot;: &quot;RESEARCH_REFERENCE&quot;,
        '''          &quot;text&quot;: &quot;Sites&quot;,
        '''          &quot;id&quot;: 400,
        '''          &quot;showpanel&quot;: false,
        '''          &quot;items&quot;: [
        '''            {
        '''              &quot;name&quot;: &quot;RESEARCH_REFERENCE_FINDAGRAVE&quot;,
        '''              &quot;id&quot;: 401,
        '''              &quot;itemtype&quot;: &quot;RIButton&quot;,
        '''              &quot;attributes&quot;: [
        '''                {
        '''                  &quot;attribute&quot;: &quot;I [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Ribbon_ResearchBar() As String
            Get
                Return ResourceManager.GetString("Ribbon_ResearchBar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tag() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tag", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to document.addEventListener(&apos;DOMContentLoaded&apos;, function () {
        '''  var x = document.createElement(&apos;STYLE&apos;);
        '''  x.appendChild(document.createTextNode(&apos;::-webkit-scrollbar {width: 14px;background-color: #2e2e2e;}&apos;));
        '''  x.appendChild(document.createTextNode(&apos;::-webkit-scrollbar-corner {background-color: #2e2e2e;}&apos;));
        '''  x.appendChild(document.createTextNode(&apos;::-webkit-scrollbar-thumb {width: 14px;border-color: #2e2e2e;border-style: solid;border-size: .5px;background-color: #4d4d4d;}&apos;));
        '''  x.appendChild(document. [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property WEBAPI() As String
            Get
                Return ResourceManager.GetString("WEBAPI", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
