'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("AncestryAssistant.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ANCESTRY() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ANCESTRY", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to if (typeof ancestryAssistant === &apos;undefined&apos;)
        '''	ancestryAssistant = {};
        '''
        '''ancestryAssistant.MessageTypes = {};
        '''ancestryAssistant.MessageTypes.MT_PERSON = &apos;person&apos;;
        '''ancestryAssistant.MessageTypes.MT_ACCOUNT = &apos;account&apos;;
        '''ancestryAssistant.MessageTypes.MT_TREES = &apos;trees&apos;;
        '''ancestryAssistant.MessageTypes.MT_PAGE = &apos;page&apos;;
        '''ancestryAssistant.MessageTypes.MT_TABLEDATA = &apos;tabledata&apos;;
        '''ancestryAssistant.MessageTypes.MT_FINDAGRAVE = &apos;findagrave&apos;;
        '''
        '''ancestryAssistant.postMessage = function (msgType, msgKey, payl [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property AssistantAPI() As String
            Get
                Return ResourceManager.GetString("AssistantAPI", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to {
        '''  &quot;bars&quot;: [
        '''    {
        '''      &quot;name&quot;: &quot;Notebook&quot;,
        '''      &quot;id&quot;: 100,
        '''      &quot;visible&quot;: true,
        '''      &quot;enabled&quot;: true,
        '''      &quot;showpage&quot;: false,
        '''      &quot;usesgroups&quot;: [
        '''        {
        '''          &quot;id&quot;: 1
        '''        }
        '''      ]
        '''    }
        '''  ],
        '''  &quot;groups&quot;: [
        '''    {
        '''      &quot;name&quot;: &quot;Clipboard&quot;,
        '''      &quot;id&quot;: 1,
        '''      &quot;visible&quot;: true,
        '''      &quot;enabled&quot;: true,
        '''      &quot;showpanel&quot;: false,
        '''      &quot;usesitems&quot;: [
        '''        {
        '''          &quot;id&quot;: 1
        '''        }
        '''      ]
        '''    }
        '''  ],
        '''  &quot;items&quot;: [
        '''    {
        '''      &quot;name&quot;: &quot;Paste&quot;,
        '''      &quot;id&quot;: 1 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Ribbon() As String
            Get
                Return ResourceManager.GetString("Ribbon", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
