'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("D:\Geneology\Apps\AncestryAssistant\AncestryAssistant\Ancestors\")>  _
        Public Property AncestorsPath() As String
            Get
                Return CType(Me("AncestorsPath"),String)
            End Get
            Set
                Me("AncestorsPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("700, 500")>  _
        Public Property MainForm_ClientSize() As Global.System.Drawing.size
            Get
                Return CType(Me("MainForm_ClientSize"),Global.System.Drawing.size)
            End Get
            Set
                Me("MainForm_ClientSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property ANCESTRY_SHOW_TOOLBAR() As Boolean
            Get
                Return CType(Me("ANCESTRY_SHOW_TOOLBAR"),Boolean)
            End Get
            Set
                Me("ANCESTRY_SHOW_TOOLBAR") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Certificate,Document,Newspaper,Photo")>  _
        Public Property IMAGE_CATEGORIES() As String
            Get
                Return CType(Me("IMAGE_CATEGORIES"),String)
            End Get
            Set
                Me("IMAGE_CATEGORIES") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Birth,Death,Marriage")>  _
        Public Property IMAGE_TYPE_Certificate() As String
            Get
                Return CType(Me("IMAGE_TYPE_Certificate"),String)
            End Get
            Set
                Me("IMAGE_TYPE_Certificate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Land,Will")>  _
        Public Property IMAGE_TYPE_Document() As String
            Get
                Return CType(Me("IMAGE_TYPE_Document"),String)
            End Get
            Set
                Me("IMAGE_TYPE_Document") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Obituary,Marriage")>  _
        Public Property IMAGE_TYPE_Newspaper() As String
            Get
                Return CType(Me("IMAGE_TYPE_Newspaper"),String)
            End Get
            Set
                Me("IMAGE_TYPE_Newspaper") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Headstone,Portrait,Profile")>  _
        Public Property IMAGE_TYPE_Photo() As String
            Get
                Return CType(Me("IMAGE_TYPE_Photo"),String)
            End Get
            Set
                Me("IMAGE_TYPE_Photo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property UI_ML_VIS() As Boolean
            Get
                Return CType(Me("UI_ML_VIS"),Boolean)
            End Get
            Set
                Me("UI_ML_VIS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property UI_MR_VIS() As Boolean
            Get
                Return CType(Me("UI_MR_VIS"),Boolean)
            End Get
            Set
                Me("UI_MR_VIS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("800")>  _
        Public Property UI_ML_WIDTH() As Integer
            Get
                Return CType(Me("UI_ML_WIDTH"),Integer)
            End Get
            Set
                Me("UI_ML_WIDTH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property UI_MB_VIS() As Boolean
            Get
                Return CType(Me("UI_MB_VIS"),Boolean)
            End Get
            Set
                Me("UI_MB_VIS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("400")>  _
        Public Property UI_MB_HEIGHT() As Integer
            Get
                Return CType(Me("UI_MB_HEIGHT"),Integer)
            End Get
            Set
                Me("UI_MB_HEIGHT") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property UI_LT_VIS() As Boolean
            Get
                Return CType(Me("UI_LT_VIS"),Boolean)
            End Get
            Set
                Me("UI_LT_VIS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property UI_LB_VIS() As Boolean
            Get
                Return CType(Me("UI_LB_VIS"),Boolean)
            End Get
            Set
                Me("UI_LB_VIS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("400")>  _
        Public Property UI_LT_HEIGHT() As Integer
            Get
                Return CType(Me("UI_LT_HEIGHT"),Integer)
            End Get
            Set
                Me("UI_LT_HEIGHT") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("300")>  _
        Public Property UI_L_WIDTH() As Integer
            Get
                Return CType(Me("UI_L_WIDTH"),Integer)
            End Get
            Set
                Me("UI_L_WIDTH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property UI_RT_VIS() As Boolean
            Get
                Return CType(Me("UI_RT_VIS"),Boolean)
            End Get
            Set
                Me("UI_RT_VIS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property UI_RB_VIS() As Boolean
            Get
                Return CType(Me("UI_RB_VIS"),Boolean)
            End Get
            Set
                Me("UI_RB_VIS") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("400")>  _
        Public Property UI_RT_HEIGHT() As Integer
            Get
                Return CType(Me("UI_RT_HEIGHT"),Integer)
            End Get
            Set
                Me("UI_RT_HEIGHT") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("300")>  _
        Public Property UI_R_WIDTH() As Integer
            Get
                Return CType(Me("UI_R_WIDTH"),Integer)
            End Get
            Set
                Me("UI_R_WIDTH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ANCESTOR")>  _
        Public Property UI_LT_CTL() As String
            Get
                Return CType(Me("UI_LT_CTL"),String)
            End Get
            Set
                Me("UI_LT_CTL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ANCESTORS")>  _
        Public Property UI_LB_CTL() As String
            Get
                Return CType(Me("UI_LB_CTL"),String)
            End Get
            Set
                Me("UI_LB_CTL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ANCESTRY")>  _
        Public Property UI_ML_CTL() As String
            Get
                Return CType(Me("UI_ML_CTL"),String)
            End Get
            Set
                Me("UI_ML_CTL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("400")>  _
        Public Property UI_MR_WIDTH() As Integer
            Get
                Return CType(Me("UI_MR_WIDTH"),Integer)
            End Get
            Set
                Me("UI_MR_WIDTH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("65171586")>  _
        Public Property ANCESTRY_TREE_ID() As String
            Get
                Return CType(Me("ANCESTRY_TREE_ID"),String)
            End Get
            Set
                Me("ANCESTRY_TREE_ID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("424, 322")>  _
        Public Property APP_CLIENTSIZE() As Global.System.Drawing.Size
            Get
                Return CType(Me("APP_CLIENTSIZE"),Global.System.Drawing.Size)
            End Get
            Set
                Me("APP_CLIENTSIZE") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property DOCK_WEBBROWSER_LOC() As Integer
            Get
                Return CType(Me("DOCK_WEBBROWSER_LOC"),Integer)
            End Get
            Set
                Me("DOCK_WEBBROWSER_LOC") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property DOCK_ANCESTORSLIST_LOC() As Integer
            Get
                Return CType(Me("DOCK_ANCESTORSLIST_LOC"),Integer)
            End Get
            Set
                Me("DOCK_ANCESTORSLIST_LOC") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("6")>  _
        Public Property DOCK_ANCESTORATTRIBUTES_LOC() As Integer
            Get
                Return CType(Me("DOCK_ANCESTORATTRIBUTES_LOC"),Integer)
            End Get
            Set
                Me("DOCK_ANCESTORATTRIBUTES_LOC") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property DOCK_CENSUS_LOC() As Integer
            Get
                Return CType(Me("DOCK_CENSUS_LOC"),Integer)
            End Get
            Set
                Me("DOCK_CENSUS_LOC") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property DOCK_GALLERY_LOC() As Integer
            Get
                Return CType(Me("DOCK_GALLERY_LOC"),Integer)
            End Get
            Set
                Me("DOCK_GALLERY_LOC") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property DOCK_NOTEBOOK_LOC() As Integer
            Get
                Return CType(Me("DOCK_NOTEBOOK_LOC"),Integer)
            End Get
            Set
                Me("DOCK_NOTEBOOK_LOC") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ancestryassistant")>  _
        Public ReadOnly Property WEB_HOSTNAME() As String
            Get
                Return CType(Me("WEB_HOSTNAME"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("D:\Geneology\Apps\AncestryAssistant\AncestryAssistant\Ancestors\")>  _
        Public ReadOnly Property WEB_VIRTUALPATH() As String
            Get
                Return CType(Me("WEB_VIRTUALPATH"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property DOCK_ANCESTORSLISTWEB_LOC() As Integer
            Get
                Return CType(Me("DOCK_ANCESTORSLISTWEB_LOC"),Integer)
            End Get
            Set
                Me("DOCK_ANCESTORSLISTWEB_LOC") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property DOCK_IMAGEGALLERYWEB_LOC() As Integer
            Get
                Return CType(Me("DOCK_IMAGEGALLERYWEB_LOC"),Integer)
            End Get
            Set
                Me("DOCK_IMAGEGALLERYWEB_LOC") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property DOCK_CENSUSWEB_LOC() As Integer
            Get
                Return CType(Me("DOCK_CENSUSWEB_LOC"),Integer)
            End Get
            Set
                Me("DOCK_CENSUSWEB_LOC") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.AncestryAssistant.My.MySettings
            Get
                Return Global.AncestryAssistant.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
