'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("D:\Geneology\Ancestors\")>  _
        Public Property AncestorsPath() As String
            Get
                Return CType(Me("AncestorsPath"),String)
            End Get
            Set
                Me("AncestorsPath") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("892, 546")>  _
        Public Property MainForm_ClientSize() As Global.System.Drawing.Size
            Get
                Return CType(Me("MainForm_ClientSize"),Global.System.Drawing.Size)
            End Get
            Set
                Me("MainForm_ClientSize") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("239")>  _
        Public Property MainSplitter() As Integer
            Get
                Return CType(Me("MainSplitter"),Integer)
            End Get
            Set
                Me("MainSplitter") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property MainSplitter_Panel1Collapsed() As Boolean
            Get
                Return CType(Me("MainSplitter_Panel1Collapsed"),Boolean)
            End Get
            Set
                Me("MainSplitter_Panel1Collapsed") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property MainSplitter_Panel2Collapsed() As Boolean
            Get
                Return CType(Me("MainSplitter_Panel2Collapsed"),Boolean)
            End Get
            Set
                Me("MainSplitter_Panel2Collapsed") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property SideSplitter_Panel1Collapsed() As Boolean
            Get
                Return CType(Me("SideSplitter_Panel1Collapsed"),Boolean)
            End Get
            Set
                Me("SideSplitter_Panel1Collapsed") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property SideSplitter_Panel2Collapsed() As Boolean
            Get
                Return CType(Me("SideSplitter_Panel2Collapsed"),Boolean)
            End Get
            Set
                Me("SideSplitter_Panel2Collapsed") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("188")>  _
        Public Property SideSplitter() As Integer
            Get
                Return CType(Me("SideSplitter"),Integer)
            End Get
            Set
                Me("SideSplitter") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property SideSplitter_Panel1Visible() As Boolean
            Get
                Return CType(Me("SideSplitter_Panel1Visible"),Boolean)
            End Get
            Set
                Me("SideSplitter_Panel1Visible") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property SideSplitter_Panel2Visible() As Boolean
            Get
                Return CType(Me("SideSplitter_Panel2Visible"),Boolean)
            End Get
            Set
                Me("SideSplitter_Panel2Visible") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("175")>  _
        Public Property Ancestor_Name_Width() As Integer
            Get
                Return CType(Me("Ancestor_Name_Width"),Integer)
            End Get
            Set
                Me("Ancestor_Name_Width") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("175")>  _
        Public Property Ancestor_Death_Width() As Integer
            Get
                Return CType(Me("Ancestor_Death_Width"),Integer)
            End Get
            Set
                Me("Ancestor_Death_Width") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("60")>  _
        Public Property Ancestor_Birth_Width() As Integer
            Get
                Return CType(Me("Ancestor_Birth_Width"),Integer)
            End Get
            Set
                Me("Ancestor_Birth_Width") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("75")>  _
        Public Property Ancestor_Task_Item() As Integer
            Get
                Return CType(Me("Ancestor_Task_Item"),Integer)
            End Get
            Set
                Me("Ancestor_Task_Item") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("200")>  _
        Public Property Ancestor_Task_Comments() As Integer
            Get
                Return CType(Me("Ancestor_Task_Comments"),Integer)
            End Get
            Set
                Me("Ancestor_Task_Comments") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("28, 388")>  _
        Public Property TB_ANCESTRY_LOC() As Global.System.Drawing.Point
            Get
                Return CType(Me("TB_ANCESTRY_LOC"),Global.System.Drawing.Point)
            End Get
            Set
                Me("TB_ANCESTRY_LOC") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("24, 3")>  _
        Public Property TB_WEB_LOC() As Global.System.Drawing.Point
            Get
                Return CType(Me("TB_WEB_LOC"),Global.System.Drawing.Point)
            End Get
            Set
                Me("TB_WEB_LOC") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("242, 24")>  _
        Public Property TB_RESEARCH_LOC() As Global.System.Drawing.Point
            Get
                Return CType(Me("TB_RESEARCH_LOC"),Global.System.Drawing.Point)
            End Get
            Set
                Me("TB_RESEARCH_LOC") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Segoe UI Semibold, 9pt, style=Bold")>  _
        Public Property APP_FONT() As Global.System.Drawing.Font
            Get
                Return CType(Me("APP_FONT"),Global.System.Drawing.Font)
            End Get
            Set
                Me("APP_FONT") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ControlText")>  _
        Public Property FORM_A_FG() As Global.System.Drawing.Color
            Get
                Return CType(Me("FORM_A_FG"),Global.System.Drawing.Color)
            End Get
            Set
                Me("FORM_A_FG") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.AncestryAssistant.My.MySettings
            Get
                Return Global.AncestryAssistant.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
